/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#fffeff",
        "on-surface-variant": "#414752",
        "primary": "#005dac",
        "surface-tint": "#005faf",
        "background": "#f8f9fa",
        "on-secondary-fixed": "#0f1d25",
        "on-tertiary": "#ffffff",
        "surface": "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1d",
        "on-secondary-fixed-variant": "#3b4951",
        "inverse-surface": "#2e3132",
        "surface-container": "#edeeef",
        "on-secondary-container": "#56656e",
        "on-error": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "tertiary-fixed-dim": "#ffb688",
        "tertiary": "#944700",
        "on-secondary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "secondary": "#526069",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "secondary-fixed": "#d6e5ef",
        "outline-variant": "#c1c6d4",
        "on-tertiary-fixed-variant": "#733600",
        "on-background": "#191c1d",
        "surface-container-highest": "#e1e3e4",
        "surface-container-low": "#f3f4f5",
        "secondary-fixed-dim": "#bac9d3",
        "outline": "#717783",
        "primary-fixed": "#d4e3ff",
        "on-primary": "#ffffff",
        "secondary-container": "#d3e2ed",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-fixed": "#ffdbc7",
        "on-tertiary-fixed": "#311300",
        "primary-container": "#1976d2",
        "primary-fixed-dim": "#a5c8ff",
        "on-primary-fixed": "#001c3a",
        "surface-bright": "#f8f9fa",
        "error": "#ba1a1a",
        "surface-dim": "#d9dadb",
        "inverse-primary": "#a5c8ff",
        "tertiary-container": "#ba5b00",
        "on-primary-fixed-variant": "#004786",
        "on-primary-container": "#fffdff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ['"Styrene B"', '"Outfit"', "sans-serif"],
        "sans": ['"Styrene B"', '"Outfit"', "sans-serif"],
        "label": ['"Styrene B"', '"Outfit"', "sans-serif"],
        "body": ['"Tiempos Text"', '"Source Serif 4"', "Georgia", "serif"],
        "serif": ['"Tiempos Text"', '"Source Serif 4"', "Georgia", "serif"]
      }
    },
  },
  plugins: [],
}
