import os
import base64
from io import BytesIO
from jinja2 import Template
from xhtml2pdf import pisa
from datetime import datetime
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

def generate_trend_chart(trend_data):
    if not trend_data or len(trend_data) == 0:
        return ""
    # Ensure exactly 12 points
    if len(trend_data) < 12:
        trend_data = trend_data + [trend_data[-1]] * (12 - len(trend_data))
    elif len(trend_data) > 12:
        trend_data = trend_data[-12:]
        
    plt.figure(figsize=(8, 2.5), dpi=150)
    plt.plot(range(1, 13), trend_data, marker='o', markersize=5, color='#005dac', linewidth=2)
    plt.fill_between(range(1, 13), trend_data, alpha=0.1, color='#005dac')
    plt.ylim(0, 100)
    plt.xlim(1, 12)
    plt.xticks(range(1, 13), [f"M{i}" for i in range(1, 13)], color='#6b7280')
    plt.yticks(color='#6b7280')
    plt.grid(axis='y', linestyle='--', alpha=0.4)
    plt.gca().spines['top'].set_visible(False)
    plt.gca().spines['right'].set_visible(False)
    plt.gca().spines['left'].set_color('#e5e7eb')
    plt.gca().spines['bottom'].set_color('#e5e7eb')
    plt.tight_layout()
    
    buf = BytesIO()
    plt.savefig(buf, format='png', transparent=True)
    buf.seek(0)
    b64 = base64.b64encode(buf.read()).decode('utf-8')
    plt.close()
    return f"data:image/png;base64,{b64}"


REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    @page {
        size: a4 portrait;
        margin: 1.5cm;
        @frame header {
            -pdf-frame-content: header_content;
            top: 1cm; margin-left: 1.5cm; margin-right: 1.5cm; height: 1cm;
        }
        @frame footer {
            -pdf-frame-content: footer_content;
            bottom: 1cm; margin-left: 1.5cm; margin-right: 1.5cm; height: 1cm;
        }
    }
    body {
        font-family: Helvetica, sans-serif;
        color: #1f2937;
        line-height: 1.6;
    }
    h1, h2, h3 { color: #005dac; font-family: Times, serif; }
    
    .badge {
        display: inline-block;
        padding: 6px 14px;
        border-radius: 9999px;
        font-weight: bold;
        font-size: 0.9em;
    }
    .badge-green { background-color: #d1fae5; color: #065f46; border: 1px solid #10b981; }
    .badge-red { background-color: #fee2e2; color: #991b1b; border: 1px solid #ef4444; }
    
    .grade-badge {
        display: inline-block;
        padding: 8px 20px;
        border-radius: 12px;
        font-weight: bold;
        font-size: 1.4em;
        margin-top: 10px;
        border: 2px solid;
    }
    .grade-A { background-color: #dcfce7; color: #166534; border-color: #22c55e; }
    .grade-B { background-color: #d1fae5; color: #065f46; border-color: #10b981; }
    .grade-C { background-color: #fef08a; color: #854d0e; border-color: #eab308; }
    .grade-D { background-color: #fed7aa; color: #9a3412; border-color: #f97316; }
    .grade-F { background-color: #fee2e2; color: #991b1b; border-color: #ef4444; }

    .fallback-note {
        color: #d97706;
        font-size: 0.8em;
        font-style: italic;
        margin-top: 4px;
        display: block;
    }
    .score-circle {
        font-size: 3em;
        font-weight: bold;
        color: #005dac;
    }
    .page-break { -pdf-pagebreak: true; }
    
    /* Signal Cards */
    .signal-card {
        page-break-inside: avoid;
        background-color: #ffffff;
        border: 1px solid #e5e7eb;
        border-radius: 12px;
        padding: 18px;
        margin-bottom: 20px;
    }
    .signal-header {
        margin-bottom: 12px;
        border-bottom: 1px solid #f3f4f6;
        padding-bottom: 10px;
    }
    .signal-title {
        font-size: 1.1em;
        font-weight: bold;
        color: #111827;
        margin: 0;
    }
    .progress-bg {
        background-color: #f3f4f6;
        border-radius: 6px;
        height: 10px;
        width: 100%;
        margin: 8px 0;
    }
    .progress-fill {
        background-color: #005dac;
        height: 10px;
        border-radius: 6px;
    }
    
    .chart-container {
        text-align: center;
        margin: 30px 0;
        border: 1px solid #e5e7eb;
        border-radius: 12px;
        padding: 20px;
        background-color: #f9fafb;
    }
    .chart-img {
        width: 100%;
        max-width: 600px;
    }
    
    ul.action-list { padding-left: 20px; }
    ul.action-list li { margin-bottom: 12px; }
</style>
</head>
<body>
    <div id="header_content">
        <strong style="color:#005dac;">TrustLens</strong> <span style="color:#9ca3af;">|</span> Privacy &amp; Security Report for {{ platform.title() }}
    </div>
    
    <div id="footer_content" style="text-align: right; font-size: 0.8em; color: #6b7280;">
        Generated by TrustLens - Page <pdf:pagenumber>
    </div>

    <h1 style="text-align: center; font-size: 2.8em; margin-bottom: 0;">TrustLens Report</h1>
    <h2 style="text-align: center; color: #4b5563; margin-top: 5px;">{{ platform.title() }}</h2>
    <p style="text-align: center; color: #6b7280;">Generated on: {{ date }}</p>
    
    <div style="text-align: center; margin: 50px 0;">
        <div class="score-circle">{{ data.score }} <span style="font-size: 0.5em; color: #9ca3af;">/ 100</span></div>
        <div class="grade-badge grade-{{ data.grade[0] if data.grade else 'C' }}">Grade: {{ data.grade }}</div>
        <p style="margin-top: 15px; font-size: 1.1em; max-width: 80%; margin-left: auto; margin-right: auto; color: #4b5563;">
            {{ data.grade_desc }}
        </p>
    </div>

    <div style="text-align: center; margin-bottom: 40px;">
        <span class="badge {% if data.dpdp_compliant %}badge-green{% else %}badge-red{% endif %}">
            DPDP Act 2023: {% if data.dpdp_compliant %}Compliant{% else %}Non-Compliant{% endif %}
        </span>
    </div>

    <div style="background-color: #f9fafb; padding: 20px; border-radius: 12px; border: 1px solid #e5e7eb;">
        <h3 style="margin-top: 0;">About {{ platform.title() }}</h3>
        <p style="margin-bottom: 0; color: #374151;">{{ data.description }}</p>
    </div>

    <div class="page-break"></div>

    <h2>Signal Breakdown</h2>
    
    {% for key, signal in data.signals.items() %}
    <div class="signal-card">
        <div class="signal-header">
            <table style="width: 100%;">
                <tr>
                    <td style="width: 70%;">
                        <h3 class="signal-title">{{ key.replace('_', ' ').title() }}</h3>
                    </td>
                    <td style="width: 30%; text-align: right;">
                        <strong style="font-size: 1.2em; color: #005dac;">{{ signal.score }}</strong> / {{ signal.max }}
                    </td>
                </tr>
            </table>
            
            <div class="progress-bg">
                <div class="progress-fill" style="width: {{ (signal.score / signal.max * 100)|round(0) }}%;"></div>
            </div>
            
            {% if signal.is_fallback %}
            <span class="fallback-note">(estimated &mdash; analysis unavailable)</span>
            {% endif %}
        </div>
        <div style="color: #4b5563;">
            {{ signal.summary }}
        </div>
    </div>
    {% endfor %}

    <h2>12-Month Score Trend</h2>
    <div class="chart-container">
        {% if chart_b64 %}
        <img src="{{ chart_b64 }}" class="chart-img" />
        {% else %}
        <p>Chart data unavailable.</p>
        {% endif %}
    </div>
    
    <div style="margin-top: 40px;">
        <h2>Action Steps</h2>
        <ul class="action-list">
            {% for step in data.action_steps %}
            <li>{{ step }}</li>
            {% endfor %}
        </ul>
    </div>

</body>
</html>
"""

def generate_pdf_report(platform: str, data: dict) -> BytesIO:
    chart_b64 = generate_trend_chart(data.get("trend", []))
    
    template = Template(REPORT_TEMPLATE)
    html_content = template.render(
        platform=platform,
        data=data,
        chart_b64=chart_b64,
        date=datetime.now().strftime("%B %d, %Y")
    )
    
    pdf_buffer = BytesIO()
    pisa_status = pisa.CreatePDF(
        html_content,
        dest=pdf_buffer
    )
    
    if pisa_status.err:
        raise Exception(f"PDF generation failed: {pisa_status.err}")
        
    pdf_buffer.seek(0)
    return pdf_buffer
    return pdf_buffer
