import os
from io import BytesIO
from jinja2 import Template
from xhtml2pdf import pisa
from datetime import datetime

REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    @page {
        size: a4 portrait;
        margin: 1.5cm;
        @frame header {
            -pdf-frame-content: header_content;
            top: 1cm; margin-left: 1.5cm; margin-right: 1.5cm; height: 1cm;
        }
        @frame footer {
            -pdf-frame-content: footer_content;
            bottom: 1cm; margin-left: 1.5cm; margin-right: 1.5cm; height: 1cm;
        }
    }
    body {
        font-family: Helvetica, sans-serif;
        color: #1f2937;
        line-height: 1.5;
    }
    h1, h2, h3 { color: #005dac; font-family: Times, serif; }
    .badge {
        display: inline-block;
        padding: 5px 10px;
        background-color: #f3f4f6;
        border: 1px solid #e5e7eb;
        border-radius: 5px;
        font-weight: bold;
    }
    .badge-green { background-color: #d1fae5; color: #065f46; border-color: #10b981; }
    .badge-red { background-color: #fee2e2; color: #991b1b; border-color: #ef4444; }
    .fallback-note {
        color: #b45309;
        font-size: 0.85em;
        font-style: italic;
    }
    .score-circle {
        font-size: 2.5em;
        font-weight: bold;
        color: #005dac;
    }
    .page-break { -pdf-pagebreak: true; }
    
    table.signals { width: 100%; border-collapse: collapse; margin-top: 20px; }
    table.signals th, table.signals td { border: 1px solid #e5e7eb; padding: 12px; text-align: left; vertical-align: top; }
    table.signals th { background-color: #f3f4f6; }
    
    /* Bar chart using table */
    table.chart { width: 100%; border-bottom: 2px solid #ccc; height: 150px; margin-top: 20px; }
    table.chart td { vertical-align: bottom; text-align: center; padding: 0 5px; }
    .bar { background-color: #005dac; width: 100%; }
    .bar-label { font-size: 0.7em; margin-top: 5px; color: #6b7280; }
</style>
</head>
<body>
    <div id="header_content">
        <strong style="color:#005dac;">TrustLens</strong> | Privacy &amp; Security Report for {{ platform.title() }}
    </div>
    
    <div id="footer_content" style="text-align: right; font-size: 0.8em; color: #6b7280;">
        Generated by TrustLens - Page <pdf:pagenumber>
    </div>

    <h1 style="text-align: center; font-size: 2.5em;">TrustLens Report</h1>
    <h2 style="text-align: center; color: #374151;">{{ platform.title() }}</h2>
    <p style="text-align: center; color: #6b7280;">Generated on: {{ date }}</p>
    
    <div style="text-align: center; margin: 40px 0;">
        <div class="score-circle">{{ data.score }} / 100</div>
        <h2 style="margin-top: 5px;">Grade: {{ data.grade }}</h2>
        <p style="margin: 0;">{{ data.grade_desc }}</p>
    </div>

    <div style="text-align: center; margin-bottom: 40px;">
        <span class="badge {% if data.dpdp_compliant %}badge-green{% else %}badge-red{% endif %}">
            DPDP Act 2023: {% if data.dpdp_compliant %}Compliant{% else %}Non-Compliant{% endif %}
        </span>
    </div>

    <h3>About {{ platform.title() }}</h3>
    <p>{{ data.description }}</p>

    <div class="page-break"></div>

    <h2>Signal Breakdown</h2>
    <table class="signals">
        <thead>
            <tr>
                <th style="width: 25%;">Signal</th>
                <th style="width: 20%;">Score</th>
                <th style="width: 55%;">Analysis</th>
            </tr>
        </thead>
        <tbody>
            {% for key, signal in data.signals.items() %}
            <tr>
                <td><strong>{{ key.upper() }}</strong></td>
                <td>
                    <strong style="font-size: 1.2em;">{{ signal.score }}</strong> / {{ signal.max }}<br>
                    {% if signal.is_fallback %}
                    <div class="fallback-note">(estimated &mdash; analysis unavailable)</div>
                    {% endif %}
                </td>
                <td>{{ signal.summary }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="page-break"></div>

    <h2>12-Month Score Trend</h2>
    <table class="chart">
        <tr>
            {% for val in data.trend %}
            <td>
                <div style="font-size: 0.7em; margin-bottom: 2px;">{{ val }}</div>
                <div class="bar" style="height: {{ val }}px;"></div>
                <div class="bar-label">M{{ loop.index }}</div>
            </td>
            {% endfor %}
        </tr>
    </table>
    
    <div style="margin-top: 40px;">
        <h2>Action Steps</h2>
        <ul>
            {% for step in data.action_steps %}
            <li style="margin-bottom: 10px;">{{ step }}</li>
            {% endfor %}
        </ul>
    </div>

</body>
</html>
"""

def generate_pdf_report(platform: str, data: dict) -> BytesIO:
    template = Template(REPORT_TEMPLATE)
    html_content = template.render(
        platform=platform,
        data=data,
        date=datetime.now().strftime("%B %d, %Y")
    )
    
    pdf_buffer = BytesIO()
    # Create PDF
    pisa_status = pisa.CreatePDF(
        html_content,
        dest=pdf_buffer
    )
    
    if pisa_status.err:
        raise Exception(f"PDF generation failed: {pisa_status.err}")
        
    pdf_buffer.seek(0)
    return pdf_buffer
